# GoogleHome:
#   Addr: # Google Home IP address
#   Port: 8009 # GoogleHome port number 
#   Detach: true  # Optional
#   ForceDetach: true # Optional
#   Volume: 0.5
#   MaxDuration: 5 # the message will be interrupted when this amount of time (in seconds) has passed

# Voicevox:
#   SpeakerID: 3 
#   OpenJtalkDictDir: "open_jtalk_dic_utf_8-1.11" # You have to specify Open JTalk's dict path

# Slack:
#   Token: # Slack bot token, which has permissions of app_mentions:read, chat:write, and users:read, (and optinally, chat:write.customize)
#   AppLevelToken: # Slack App level token, which has a scopeof connections:write.
#   Icon: # (optional) icon emoji You can use this if you add chat:write.customize permission.
